apiVersion: v1
kind: Pod
metadata:
  name: httpd
  namespace: apps
  labels:
    app.kubernetes.io/name: httpd
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80

